---
- hosts: app-server
  become: true
  gather_facts: yes
  name: install and configure docker
  roles:
  # install and configure docker service
    - { role: docker, become: True, tags: docker_setup }