---
- hosts: app-server
  become: true
  gather_facts: yes
  name: install and configure app server
  roles:
  # preparing server and hardening
    - { role: preparing_server, become: True, tags: preparing_server }