---
- name: Stop and Disable ufw service if started
  ansible.builtin.service:
    name: ufw
    state: stopped
    enabled: no

- name: Stop and Disable postfix service if started
  ansible.builtin.service:
    name: postfix
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Set timezone to Asia/Tehran
  community.general.timezone:
    name: Asia/Tehran
  notify: Restart ntp

- name: Make sshd configuration file.
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: Restart ssh

- name: Make iptables configuration file.
  template:
    src: iptables.j2
    dest: /etc/iptables/rules.v4

- name: restore iptables state from a file
  community.general.iptables_state:
    state: restored
    path: /etc/iptables/rules.v4
    noflush: true
  notify: Restart iptables
